pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Clone Repo') {
            steps {
                // Print the branch and clone repo
                sh 'git branch'
                git credentialsId: '5821905a-801f-4c61-bcdc-6d4ef34dbf0e', url: 'https://github.com/iankerich254/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh '''
                        python3 -m venv $VENV
                        . $VENV/bin/activate
                        pip3 install --upgrade pip
                        pip3 install -r messaging_app/requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh '''
                        . $VENV/bin/activate
                        pytest --junitxml=test-results.xml
                    '''
                }
            }
            post {
                always {
                    junit 'messaging_app/test-results.xml'
                }
            }
        }
    }
}
