apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-green
  labels:
    app: messaging
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging
      version: green
  template:
    metadata:
      labels:
        app: messaging
        version: green
    spec:
      containers:
        - name: messaging-container
          image: my_current_django_image:2.0 
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
